{   u'city': {   u'coord': {   u'lat': 46.477474, u'lon': 30.732622},
                 u'country': u'UA',
                 u'id': 698740,
                 u'name': u'Odessa',
                 u'population': 0},
    u'cnt': 14,
    u'cod': u'200',
    u'list': [   {   u'clouds': 80,
                     u'deg': 239,
                     u'dt': 1448010000,
                     u'humidity': 91,
                     u'pressure': 1018.63,
                     u'speed': 8.14,
                     u'temp': {   u'day': 13.41,
                                  u'eve': 13.41,
                                  u'max': 13.41,
                                  u'min': 13.18,
                                  u'morn': 13.41,
                                  u'night': 13.18},
                     u'weather': [   {   u'description': u'broken clouds',
                                         u'icon': u'04n',
                                         u'id': 803,
                                         u'main': u'Clouds'}]},
                 {   u'clouds': 48,
                     u'deg': 216,
                     u'dt': 1448096400,
                     u'humidity': 89,
                     u'pressure': 1011.52,
                     u'speed': 10.75,
                     u'temp': {   u'day': 13.63,
                                  u'eve': 13.71,
                                  u'max': 14.21,
                                  u'min': 12.71,
                                  u'morn': 12.71,
                                  u'night': 14.21},
                     u'weather': [   {   u'description': u'scattered clouds',
                                         u'icon': u'03d',
                                         u'id': 802,
                                         u'main': u'Clouds'}]},
                 {   u'clouds': 76,
                     u'deg': 207,
                     u'dt': 1448182800,
                     u'humidity': 84,
                     u'pressure': 1011.15,
                     u'speed': 15.23,
                     u'temp': {   u'day': 14.8,
                                  u'eve': 15.05,
                                  u'max': 15.05,
                                  u'min': 14.12,
                                  u'morn': 14.37,
                                  u'night': 14.12},
                     u'weather': [   {   u'description': u'broken clouds',
                                         u'icon': u'04d',
                                         u'id': 803,
                                         u'main': u'Clouds'}]},
                 {   u'clouds': 92,
                     u'deg': 22,
                     u'dt': 1448269200,
                     u'humidity': 100,
                     u'pressure': 1028.85,
                     u'rain': 13.8,
                     u'speed': 6.91,
                     u'temp': {   u'day': 10.73,
                                  u'eve': 10.96,
                                  u'max': 13.11,
                                  u'min': 9.73,
                                  u'morn': 13.11,
                                  u'night': 9.73},
                     u'weather': [   {   u'description': u'heavy intensity rain',
                                         u'icon': u'10d',
                                         u'id': 502,
                                         u'main': u'Rain'}]},
                 {   u'clouds': 44,
                     u'deg': 40,
                     u'dt': 1448355600,
                     u'humidity': 100,
                     u'pressure': 1039.67,
                     u'rain': 1.46,
                     u'speed': 8.6,
                     u'temp': {   u'day': 7.44,
                                  u'eve': 7.96,
                                  u'max': 8.04,
                                  u'min': 6.95,
                                  u'morn': 8.04,
                                  u'night': 6.95},
                     u'weather': [   {   u'description': u'light rain',
                                         u'icon': u'10d',
                                         u'id': 500,
                                         u'main': u'Rain'}]},
                 {   u'clouds': 25,
                     u'deg': 47,
                     u'dt': 1448442000,
                     u'humidity': 0,
                     u'pressure': 1035.35,
                     u'rain': 0.72,
                     u'speed': 5.51,
                     u'temp': {   u'day': 7.21,
                                  u'eve': 8.24,
                                  u'max': 9.56,
                                  u'min': 6.34,
                                  u'morn': 6.34,
                                  u'night': 9.56},
                     u'weather': [   {   u'description': u'light rain',
                                         u'icon': u'10d',
                                         u'id': 500,
                                         u'main': u'Rain'}]},
                 {   u'clouds': 42,
                     u'deg': 118,
                     u'dt': 1448528400,
                     u'humidity': 0,
                     u'pressure': 1019.22,
                     u'rain': 0.77,
                     u'speed': 5.82,
                     u'temp': {   u'day': 11.1,
                                  u'eve': 11.07,
                                  u'max': 11.37,
                                  u'min': 10.24,
                                  u'morn': 10.24,
                                  u'night': 11.37},
                     u'weather': [   {   u'description': u'light rain',
                                         u'icon': u'10d',
                                         u'id': 500,
                                         u'main': u'Rain'}]},
                 {   u'clouds': 39,
                     u'deg': 295,
                     u'dt': 1448614800,
                     u'humidity': 0,
                     u'pressure': 1014.56,
                     u'rain': 8.9,
                     u'speed': 10.06,
                     u'temp': {   u'day': 9.39,
                                  u'eve': 10.08,
                                  u'max': 10.08,
                                  u'min': 8.18,
                                  u'morn': 9.16,
                                  u'night': 8.18},
                     u'weather': [   {   u'description': u'moderate rain',
                                         u'icon': u'10d',
                                         u'id': 501,
                                         u'main': u'Rain'}]},
                 {   u'clouds': 68,
                     u'deg': 313,
                     u'dt': 1448701200,
                     u'humidity': 0,
                     u'pressure': 1028.39,
                     u'rain': 0.33,
                     u'speed': 8.03,
                     u'temp': {   u'day': 8.3,
                                  u'eve': 7.58,
                                  u'max': 8.48,
                                  u'min': 7.58,
                                  u'morn': 8.09,
                                  u'night': 8.48},
                     u'weather': [   {   u'description': u'light rain',
                                         u'icon': u'10d',
                                         u'id': 500,
                                         u'main': u'Rain'}]},
                 {   u'clouds': 41,
                     u'deg': 173,
                     u'dt': 1448787600,
                     u'humidity': 0,
                     u'pressure': 1032.62,
                     u'rain': 0.72,
                     u'speed': 8.38,
                     u'temp': {   u'day': 11.76,
                                  u'eve': 11.5,
                                  u'max': 11.76,
                                  u'min': 10.8,
                                  u'morn': 10.8,
                                  u'night': 11.5},
                     u'weather': [   {   u'description': u'light rain',
                                         u'icon': u'10d',
                                         u'id': 500,
                                         u'main': u'Rain'}]},
                 {   u'clouds': 26,
                     u'deg': 149,
                     u'dt': 1448874000,
                     u'humidity': 0,
                     u'pressure': 1034.87,
                     u'speed': 10.35,
                     u'temp': {   u'day': 12.02,
                                  u'eve': 11.52,
                                  u'max': 12.02,
                                  u'min': 11.42,
                                  u'morn': 11.5,
                                  u'night': 11.42},
                     u'weather': [   {   u'description': u'sky is clear',
                                         u'icon': u'01d',
                                         u'id': 800,
                                         u'main': u'Clear'}]},
                 {   u'clouds': 73,
                     u'deg': 136,
                     u'dt': 1448960400,
                     u'humidity': 0,
                     u'pressure': 1032.97,
                     u'rain': 1.47,
                     u'speed': 8.49,
                     u'temp': {   u'day': 11.55,
                                  u'eve': 11.09,
                                  u'max': 11.55,
                                  u'min': 11.03,
                                  u'morn': 11.3,
                                  u'night': 11.03},
                     u'weather': [   {   u'description': u'light rain',
                                         u'icon': u'10d',
                                         u'id': 500,
                                         u'main': u'Rain'}]},
                 {   u'clouds': 15,
                     u'deg': 80,
                     u'dt': 1449046800,
                     u'humidity': 0,
                     u'pressure': 1025.27,
                     u'rain': 0.88,
                     u'speed': 5.89,
                     u'temp': {   u'day': 9.91,
                                  u'eve': 9.11,
                                  u'max': 10.35,
                                  u'min': 8.98,
                                  u'morn': 10.35,
                                  u'night': 8.98},
                     u'weather': [   {   u'description': u'light rain',
                                         u'icon': u'10d',
                                         u'id': 500,
                                         u'main': u'Rain'}]},
                 {   u'clouds': 78,
                     u'deg': 104,
                     u'dt': 1449133200,
                     u'humidity': 0,
                     u'pressure': 1021.41,
                     u'rain': 1.16,
                     u'speed': 7.37,
                     u'temp': {   u'day': 9.46,
                                  u'eve': 8.93,
                                  u'max': 9.66,
                                  u'min': 8.93,
                                  u'morn': 9.09,
                                  u'night': 9.66},
                     u'weather': [   {   u'description': u'light rain',
                                         u'icon': u'10d',
                                         u'id': 500,
                                         u'main': u'Rain'}]}],
    u'message': 0.0082}
